version: '3.5'

services:
  db:
    image: postgres:12.2
    restart: on-failure
    volumes:
      - tests_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=django
    env_file:
      - ./envs/local/postgres

  web:
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    build:
          context: .
          dockerfile: tests_Dockerfile
    command: gunicorn telecine.wsgi:application --bind 0.0.0.0:8000 --log-file=/var/log/gunicorn.log --access-logfile=/var/log/gunicorn_access.log --log-level=info --workers 3 --max-requests 1000 --max-requests-jitter 50
    volumes:
      - ./:/home/app/web/
      - tests_static_volume:/home/app/web/staticfiles
      - tests_media_volume:/home/app/web/mediafiles
    ports:
      - "8000:8000"
    env_file:
      - ./envs/local/django
    depends_on:
      - db
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"

volumes:
  tests_postgres_data:
  tests_static_volume:
  tests_media_volume: